name: rainforest_biz_project
description: ''
version: 0.0.1
author: sahithya@originsnutra.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: rainforestbizproject
  parentArtefactID: sahithyaoriginsnutracomteam
  buildSystem: wheel
  author: null
  createdAt: '2025-07-19 15:15:45'
pipelines:
  pipelines/enrich_accounts:
    name: enrich_accounts
    description: ''
    author: sahithya@originsnutra.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-07-19 15:15:45'
    datasets:
      inputs:
      - gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=&tag=course_lab_sources/0.0.3&projectSubscriptionProjectId=13587&path=datasets/salesforce-Account
      - gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=&tag=course_lab_sources/0.0.3&projectSubscriptionProjectId=13587&path=datasets/salesforce-Opportunity
      outputs:
      - datasets/enriched_accounts
    subgraphs: []
    dependencies: {}
datasets:
  datasets/enriched_accounts:
    name: enriched_accounts
    description: ''
    author: sahithya@originsnutra.com
    createdAt: '2025-07-20 08:33:51'
    mode: batch
    physicalDatasets:
      workshop-fabric:
        fabricId: 30805
        datasetType: Database
        description: ''
        author: sahithya@originsnutra.com
        createdAt: '2025-07-20 08:33:51'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-07-19 15:15:45'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-07-19T15:15:45.636771Z'
  name: plibMaven
  version: 8.10.3
  id: '865819696'
  createdAt: '2025-07-19T15:15:45.636771Z'
  type: plibMaven
- modifiedAt: '2025-07-19T15:15:45.636771Z'
  name: plibPypi
  version: 1.9.49
  id: '179361757'
  createdAt: '2025-07-19T15:15:45.636771Z'
  type: plibPypi
projectDependencies:
  '13587':
    projectUID: 13587
    projectName: course_lab_sources
    repositoryPath: gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=
    version: course_lab_sources/0.0.3
    isDefault: false
    author: null
    createdAt: '2025-07-19 09:53:00'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.46
    isDefault: true
    author: null
    createdAt: '2025-07-19 09:53:00'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.10
    isDefault: true
    author: null
    createdAt: '2025-07-19 09:53:00'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
